### ISSUE TITLE
Add option to set the generation period

### ISSUE THREAD

**Issue by Schpammer** [qoomon/otp-authenticator-webapp#10]
In the official documentation for the Key-URI-Format, it is intended to pass a period-parameter to change the interval for generating new codes. (https://github.com/google/google-authenticator/wiki/Key-Uri-Format)

This should be implemented to accept a wider range of configurations.

**Comment by qoomon** [comment]
Done.

**Comment by DanielRuf** [comment]
Was this implemented and deployed on https://qoomon.github.io/otp-authenticator-webapp/?

Because the URLs from https://rootprojects.org/authenticator/ do not use the same configuration in your app. The timer is a few seconds off.

**Comment by qoomon** [comment]
it was implemented. The token that is generated is the same on both sites, however I don't know why there is a time shift for the timer.

**Comment by DanielRuf** [comment]
Ok, so I guess there is probably some small bug which causes the time shift.
Is this something that you will look into?

**Comment by qoomon** [comment]
I think it is a bug on https://rootprojects.org/authenticator/ , cause my web app time remaining circle is totally in sync with the google authenticator app  time remaining circle on my phone. May you can confirm that?

**Comment by DanielRuf** [comment]
> I think it is a bug on [rootprojects.org/authenticator](https://rootprojects.org/authenticator/) , cause my web app time remaining circle is totally in sync with the google authenticator app time remaining circle on my phone. May you can confirm that?

I can confirm this now, you are correct. I guess this issue here is related: https://git.coolaj86.com/coolaj86/browser-authenticator.js/issues/2 (unfortunately the link on npmjs was not correctly pointing to this page, probably because of https://github.com/github/dmca/blob/master/2019/05/2019-05-16-Daplie.md).

It seems https://rootprojects.org/authenticator/ is currently not optimal for testing. Thanks for taking the time to reply.

Not sure if there is a better option for debugging test URLs online.
